-- auto Generated on 2023-07-04
-- DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`(
	user_id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'userId',
	user_name VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'userName',
	birth DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'birth',
	salary DECIMAL (13,4) NOT NULL DEFAULT -1 COMMENT 'salary',
	PRIMARY KEY (user_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'user';
