spring:
  application:
    name: nacos-client-b
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:
        namespace: a734f710-9b36-41fe-8147-8a9369e16b83
        group: A_GROUP
        service: user-service
server:
  port: 8081
