services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG:
        external_url 'http://192.168.8.21:9999'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
      ports:
        - 9999:9999
        - 2222:2222
      volumes:
        - ./config:/etc/gitlab
        - ./logs:/var/log/gitlab
        - ./data:/var/opt/gitlab