server:
  port: 8081


spring:
  redis:
    # Redis服务器地址
    host: localhost
    # Redis服务器端口号
    port: 6379
    # 使用的数据库索引，默认是0
    database: 1
    # 连接超时时间
    timeout: 1800000
    # 设置密码
#    password: "123456"
    jedis:
      pool:
        min-idle: 5
        max-idle: 10
        max-wait: -1

  datasource:
    username: root
    password: 1812244d
    url: jdbc:mysql://127.0.0.1:3306/test

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.chen.entities
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.chen.redis.mapper: debug
